version: '3.9'
services:
  postgres:
    container_name: postgres_db_service
    image: postgres:12.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: web-flux_security
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
